### ISSUE TITLE
NPM build does not includes some methods

### ISSUE THREAD

**Issue by kevincastejon** [craigmw/lcdi2c#5]
hi, thanks for this module,
I have installed it through NPM with 'npm i lcdi2c' and it looks like it's not the same version than on the github repo since I can't find the "printlnAsync()" method along with others methods. Could you update the npm module?

**Comment by craigmw** [comment]
Hi Kevin:

It's been a while since I've worked on this and I really don't recall how to go about updating the NPMJS package from GitHub. I've merged a couple of updates, but I'm not sure how those merges are published on NPMJS.org. Any thoughts?

Craig

**Comment by kevincastejon** [comment]
well I don't know how to "link" an npm module with a github repo but if you still have access to your npm account you can git clone this repo on your computer and launch these commands from the repo folder: 
`npm login` (then follow the instructions and enter credentials to log in)
`npm version minor` (that will change the version number for you)
`npm publish` (that will actullaly push the updated module to npm)

**Comment by kevincastejon** [comment]
also I've seen that the async methods does not provide any callback argument, I could try to add this (important) feature, are you open to pull requests? 
Note that your module is the only one I've found that have updated its use to the new i2c-bus module and so that is the only one that allows to use 1602 lcd easily on raspberry pi nowadays. Thanks for that

**Comment by kevincastejon** [comment]
I have made my own repo which follows the arduino LiquidCrystal API, so I close this issue.
https://github.com/kevincastejon/js-raspberrypi-liquid-crystal
